#!/usr/bin/env python

# Translate the cases.

import os
from orthogram import translate_dir

if __name__ == '__main__':
    root = "cases"
    in_dir = os.path.join(root, "yaml")
    out_dir = os.path.join(root, "svg")
    translate_dir(in_dir, out_dir)
